name = "Newb X Legacy"
version = [0, 15, 0]
min_supported_mc_version = [1, 20, 80]
url = "https://github.com/KyaroFtKyyy/newb-x-kyaro/"
authors = ["Kyaro"]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§c%w
§7- An enchanced vanilla shader for Minecraft!
%v
§3https://github.com/KyaroFtKyyy/newb-x-kyaro/
'''
short = "A variant of Newb Shader for RenderDragon"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "ee72d5bb-2108-4f2e-9351-bdc228ce7b08"
module = "b0c171db-f169-4621-b5f2-fda59957c992"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "PERFORMANCE"
materials = ["RenderChunk", "Clouds"]
description = '''
§eRecommended !§r

Performance :
Low-High end devices : 
'''

[[subpack]]
define = "GR"
materials = ["RenderChunk"]
description = '''
§eGround Reflections, Great For Flexing§r

Performance :
Low-Mid End Devices :
High End Devices :
'''
[[subpack]]
define = "SL"
materials = ["Clouds"]
description = '''
§eSimple Clouds§r

Performance :
Low-High End Devices :
'''

[[subpack]]
define = "DEFAULT"
materials = [""]
description = '''
§eJust Default§r

Performance :
Low-High End Devices :
'''
